### ISSUE TITLE
Docker fails on Linux BookWorm

### ISSUE THREAD

**Issue by ryansurf** [ryansurf/cli-surf#86]

**Comment by ryansurf** [comment]
Seems like build tools & gcc had to be installed:

`RUN apk add --no-cache build-base libffi-dev`

**Comment by camrionnvmff** [comment]
You mentioned encountering issues running Docker on Linux BookWorm and needing to install build tools and gcc. You have provided a solution to install the necessary dependencies by adding the following command in the Dockerfile:

RUN apk add --no-cache build-base libffi-dev
This is an effective solution. If you are using Alpine Linux as the base image, this command will install the build tool and libffi development library.

If it still doesn't work, I suggest you switch to the Servbay deployment development environment

**Comment by ryansurf** [comment]
@camrionnvmff this reads like a bot :neutral_face:

**Comment by hotpocket** [comment]
> @camrionnvmff this reads like a bot 😐

and advertises for a product. that comment should be removed

**Comment by hotpocket** [comment]
I would like to claim this ticket for myself.  I see this as important to have functional to enable easier collab.

**Comment by ryansurf** [comment]
Hey @hotpocket

So the issue lies in pyarrow, with is a dependency for streamlit. In the `pyproject.toml` file, i removed `streamlit` and docker was able to build the image.

This would be a good place to start. Ill assign the issue to you now.

**Comment by ryansurf** [comment]
> > @camrionnvmff this reads like a bot 😐
> 
> and advertises for a product. that comment should be removed

comment has been sent to the gulag

**Comment by hotpocket** [comment]
> Hey @hotpocket
> 
> So the issue lies in pyarrow, a dependency for streamlit. In the `pyproject.toml` file, i removed the `streamlit` dependency and docker was able to build the image. We do want to be able to use streamlit going forward, so this isn't a permanent solution
> 
> This would be a good place to start. Ill assign the issue to you now.
> 
> Also, it seems like we should be using binaries, when able. There was a [problem](https://github.com/ryansurf/cli-surf/issues/84#issuecomment-2268085588) with matplotlib a few days back

I have found two things while digging on this:
- Wheel packages are meant to me portable by design, and matplotlib pulled that version that caused issues so it didn't present problems down stream. So as I read this we can continue to use wheel packages as normal.
- Alpine is small by design, but if we are trying to install lots of dependencies we end up with a lack of tools and a "large" image anyway.  The install of streamlit in an alpine docker image has been [discussed here](https://discuss.streamlit.io/t/anyone-tried-to-install-streamlit-in-alpine-docker-image/56893/4) with the suggestion that another distro be used if we want to install streamlit.  The link pointed to there has a specific section on why [alpine should not be chosen for running a python app](https://pythonspeed.com/articles/base-image-python-docker-images/) 

<br>
What direction do we want to take on this?

**Comment by ryansurf** [comment]
@hotpocket 

Thanks for looking into this. I agree, based on the links you provided it seems that Alpine isn't the ideal distro.

We were working with the Debian "slim" distro up until a [few weeks ago](https://github.com/ryansurf/cli-surf/commit/27fc6e98b8fbb56c14e9ab5afd7915031a360dca).

Perhaps we can revert back to this. If you'd like to test another image, please do

**Comment by hotpocket** [comment]
PR #107 submitted.  This uses the standard python docker image.

**Comment by hotpocket** [comment]
> @hotpocket
> 
> Thanks for looking into this. I agree, based on the links you provided it seems that Alpine isn't the ideal distro.
> 
> We were working with the Debian "slim" distro up until a [few weeks ago](https://github.com/ryansurf/cli-surf/commit/27fc6e98b8fbb56c14e9ab5afd7915031a360dca).
> 
> Perhaps we can revert back to this. If you'd like to test another image, please do

Interesting project.  Perhaps this could be a seperate ticket?  Use docker-slim to make the image as small as possible?  Maybe even push it to docker hub and have it mount a volume instead of copy it so that it can run alongside local development?
